version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: database
    restart: always
    env_file: ".env"
    ports:
      - "${DB_PORT}:5432"
    expose:
      - "${DB_PORT}"
    environment:
      - POSTGRES_USERNAME=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB:=${DB_NAME}
    volumes:
      - "db_data:/var/lib/postgresql/data"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: ".env"
    command: ["/app/docker/app.sh"]
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db

volumes:
  db_data:
    driver: local
    name: "db_data"
