"""is_open_group

Revision ID: 8684303c410f
Revises: a2c3b520bca0
Create Date: 2023-07-10 18:29:53.037811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8684303c410f'
down_revision = 'a2c3b520bca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('generalmissions_group_id_fkey', 'generalmissions', type_='foreignkey')
    op.create_foreign_key(None, 'generalmissions', 'managersgroups', ['group_id'], ['id'], ondelete='CASCADE')
    op.add_column('managersgroups', sa.Column('is_open', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managersgroups', 'is_open')
    op.drop_constraint(None, 'generalmissions', type_='foreignkey')
    op.create_foreign_key('generalmissions_group_id_fkey', 'generalmissions', 'managersgroups', ['group_id'], ['id'])
    # ### end Alembic commands ###
