"""empty message

Revision ID: c0d489712652
Revises: 1c56338775f0
Create Date: 2023-06-26 19:09:08.636908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0d489712652'
down_revision = '1c56338775f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generalmissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('managersgroups', sa.Column('manager_id', sa.Integer(), nullable=False))
    op.drop_constraint('managersgroups_user_id_fkey', 'managersgroups', type_='foreignkey')
    op.create_foreign_key(None, 'managersgroups', 'users', ['manager_id'], ['id'])
    op.drop_column('managersgroups', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managersgroups', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'managersgroups', type_='foreignkey')
    op.create_foreign_key('managersgroups_user_id_fkey', 'managersgroups', 'users', ['user_id'], ['id'])
    op.drop_column('managersgroups', 'manager_id')
    op.alter_column('generalmissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
